config/routes.rb
Rails.application.routes.draw do
  resources :messages

  root 'messages#index'

end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

def index
	@messages = Message.all
end

def show
	@message = Message.find(params[:id])
	#returns object corresponding to the given id -- id is the parameter needed by the router
end

def new
end

def create
	@message = Message.new(message_params)
	@message.save
	redirect_to @message
end

private 
	def message_params
		params.require(:message).permit(:from, :text)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MsgApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/index.html.erb
<h1>All messages</h1>
<h2>Once written, cannot be deleted</h2>
<br>

<table>
  <tr>
    <th>From</th>
    <th>Text</th>
  </tr>
 
  <% @messages.each do |message| %>
    <tr>
      <td><%= message.from %></td>
      <td><%= message.text %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Leave a message', new_message_path %>

app/views/messages/index.html_temp.erb
<h1>All messages</h1>
<h2>Once written, cannot be deleted</h2>
<br>

<table>
  <tr>
    <th>From</th>
    <th>Text</th>
  </tr>
 
  <% @messages.each do |message| %>
    <tr>
      <td><%= message.from %></td>
      <td><%= message.text %></td>
    </tr>
  <% end %>
</table>
<br>
<%= link_to 'Leave a message', new_message_path %>

app/views/messages/new.html.erb
<h1>Leave a Message</h1>

<%= form_for :message, url: messages_path do |f| %>
  <p>
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<p><%= link_to 'Back', messages_path %></p>

app/views/messages/show.html.erb
<p>
  <strong>From:</strong>
  <%= @message.from %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @message.text %>
</p>

<p><%= link_to 'Leave another message', new_message_path %></p>
<p><%= link_to 'Back', messages_path %></p>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<div> <%= link_to 'Check all messages', controller: 'messages' %></div>
<div><%= link_to 'Leave a message', controller: 'messages' %></div>